### ISSUE TITLE
Problem in code 

### ISSUE THREAD

**Issue by titoriya007** [dvlab-research/PFENet#67]
Please check this error
Traceback (most recent call last):
  File "test.py", line 263, in <module>
    main()
  File "test.py", line 86, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "test.py", line 144, in main_worker
    loss_val, mIoU_val, mAcc_val, allAcc_val, class_miou = validate(val_loader, model, criterion)
  File "test.py", line 237, in validate
    allAcc = sum(intersection_meter.sum) / (sum(target_meter.sum) + 1e-10)
TypeError: 'int' object is not iterable

**Comment by tianzhuotao** [comment]
Hi, thanks for being interested in our work.

In my exp, there is no such error reported. Please check your dataset/config preparation.

Thank you.

**Comment by wuhu-wang** [comment]
I met the same problem. Have you solved the problem

**Comment by GaoZhitao121** [comment]
I downloaded the `SegmentationClassAug. zip` dataset separately to solve the problem.
